# Generated by Django 5.0.3 on 2025-10-07 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO_PROGRAMADO', 'Ingreso Programado'), ('INGRESO_INICIADO', 'Ingreso Iniciado'), ('TAREA_ASIGNADA', 'Tarea Asignada'), ('TAREA_COMPLETADA', 'Tarea Completada'), ('PAUSA_REGISTRADA', 'Pausa Registrada'), ('INGRESO_TERMINADO', 'Ingreso Terminado'), ('DOCUMENTO_SUBIDO', 'Documento Subido')], max_length=30, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='leída')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_leida', models.DateTimeField(blank=True, null=True, verbose_name='fecha leída')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx'), models.Index(fields=['-fecha_creacion'], name='notificacio_fecha_c_667613_idx')],
            },
        ),
    ]
