# Generated by Django 5.0.3 on 2025-11-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('INGRESO_PROGRAMADO', 'Ingreso Programado'), ('INGRESO_INICIADO', 'Ingreso Iniciado'), ('TAREA_ASIGNADA', 'Tarea Asignada'), ('TAREA_COMPLETADA', 'Tarea Completada'), ('PAUSA_REGISTRADA', 'Pausa Registrada'), ('INGRESO_TERMINADO', 'Ingreso Terminado'), ('DOCUMENTO_SUBIDO', 'Documento Subido'), ('VEHICULO_LISTO_RETIRO', 'Vehículo Listo para Retiro')], max_length=30, verbose_name='tipo'),
        ),
    ]
