# Generated by Django 5.0.3 on 2025-10-07 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(verbose_name='fecha programada')),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True, verbose_name='fecha de llegada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateTimeField(blank=True, null=True, verbose_name='fecha de término')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('EN_PAUSA', 'En Pausa'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20, verbose_name='estado')),
                ('motivo', models.TextField(verbose_name='motivo del ingreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('kilometraje_ingreso', models.PositiveIntegerField(blank=True, null=True, verbose_name='kilometraje al ingreso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_como_chofer', to=settings.AUTH_USER_MODEL, verbose_name='chofer')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_supervisados', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'ingreso al taller',
                'verbose_name_plural': 'ingresos al taller',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO_INGRESO', 'Foto de Ingreso'), ('FOTO_DAÑO', 'Foto de Daño'), ('INFORME_SINIESTRO', 'Informe de Siniestro'), ('ORDEN_TRABAJO', 'Orden de Trabajo'), ('FACTURA', 'Factura'), ('OTRO', 'Otro')], max_length=30, verbose_name='tipo de documento')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/', verbose_name='archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='nombre original')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='fecha de subida')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vehiculos.vehiculo', verbose_name='vehículo')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ingresos.ingresotaller', verbose_name='ingreso')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Pausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255, verbose_name='motivo de la pausa')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fecha de fin')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='ingresos.ingresotaller', verbose_name='ingreso')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pausas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'pausa',
                'verbose_name_plural': 'pausas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('tiempo_estimado_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='tiempo estimado (min)')),
                ('tiempo_invertido_minutos', models.PositiveIntegerField(default=0, verbose_name='tiempo invertido (min)')),
                ('repuestos_utilizados', models.TextField(blank=True, verbose_name='repuestos utilizados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='fecha completada')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='ingresos.ingresotaller', verbose_name='ingreso')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='mecánico')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['estado', '-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='ingresotaller',
            index=models.Index(fields=['vehiculo', 'estado'], name='ingresos_in_vehicul_ee1e12_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresotaller',
            index=models.Index(fields=['fecha_programada'], name='ingresos_in_fecha_p_0b200c_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresotaller',
            index=models.Index(fields=['estado'], name='ingresos_in_estado_eed340_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['vehiculo', 'tipo'], name='ingresos_do_vehicul_ca7a43_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['ingreso'], name='ingresos_do_ingreso_02c627_idx'),
        ),
    ]
