# Generated by Django 5.0.3 on 2025-10-09 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 9, 5, 25, 32, 406597, tzinfo=datetime.timezone.utc), verbose_name='fecha de asignación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
    ]
