# Generated by Django 5.0.3 on 2025-10-22 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_alter_tarea_options_tarea_fecha_asignacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('ASIGNACION', 'Asignación'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('CAMBIO_PRIORIDAD', 'Cambio de Prioridad'), ('MODIFICACION', 'Modificación'), ('COMENTARIO', 'Comentario')], max_length=30, verbose_name='tipo de cambio')),
                ('campo_modificado', models.CharField(blank=True, max_length=100, verbose_name='campo modificado')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, verbose_name='valor nuevo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción del cambio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha del cambio')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ingresos.tarea', verbose_name='tarea')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_tareas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'historial de tarea',
                'verbose_name_plural': 'historiales de tareas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tarea', '-fecha'], name='ingresos_hi_tarea_i_59cb7e_idx')],
            },
        ),
    ]
