# Generated by Django 5.0.3 on 2025-11-18 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_historialtarea'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='fecha de solicitud')),
                ('fecha_estimada_ingreso', models.DateTimeField(verbose_name='fecha estimada de ingreso')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo del ingreso')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='estado')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='fecha de respuesta')),
                ('observaciones_supervisor', models.TextField(blank=True, verbose_name='observaciones del supervisor')),
                ('chofer', models.ForeignKey(limit_choices_to={'rol': 'CHOFER'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ingreso', to=settings.AUTH_USER_MODEL, verbose_name='chofer')),
                ('ingreso_taller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='ingresos.ingresotaller', verbose_name='ingreso al taller')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='supervisor que aprobó')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_ingreso', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'solicitud de ingreso',
                'verbose_name_plural': 'solicitudes de ingreso',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['vehiculo', 'estado'], name='ingresos_so_vehicul_188e93_idx'), models.Index(fields=['chofer', 'estado'], name='ingresos_so_chofer__6135a9_idx'), models.Index(fields=['estado'], name='ingresos_so_estado_705579_idx'), models.Index(fields=['-fecha_solicitud'], name='ingresos_so_fecha_s_5471d2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='solicitudingreso',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('vehiculo', 'estado'), name='unique_pending_request_per_vehicle'),
        ),
    ]
