# Generated by Django 5.0.3 on 2025-11-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_solicitudingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudingreso',
            name='ruta',
            field=models.CharField(blank=True, max_length=255, verbose_name='ruta (opcional)'),
        ),
        migrations.AddField(
            model_name='solicitudingreso',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='solicitudingreso',
            name='fecha_estimada_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha estimada de ingreso'),
        ),
    ]
