# Generated by Django 5.0.3 on 2025-11-19 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_solicitudingreso_ruta_solicitudingreso_telefono_and_more'),
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('patente', models.CharField(max_length=20, verbose_name='patente')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('motivo', models.TextField(blank=True, help_text='Razón del ingreso a la planta', verbose_name='motivo')),
                ('chofer_nombre', models.CharField(blank=True, max_length=200, verbose_name='nombre del chofer')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_chofer', to=settings.AUTH_USER_MODEL, verbose_name='chofer')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_guardados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por (guardia)')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_guardia', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'registro de guardia',
                'verbose_name_plural': 'registros de guardia',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['vehiculo', '-fecha_registro'], name='ingresos_re_vehicul_1b15af_idx'), models.Index(fields=['-fecha_registro'], name='ingresos_re_fecha_r_0267aa_idx')],
            },
        ),
    ]
