# Generated by Django 5.0.3 on 2025-11-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0006_registroguardia'),
    ]

    operations = [
        # Add fecha_salida field first
        migrations.AddField(
            model_name='registroguardia',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de salida'),
        ),
        # Rename fecha_registro to fecha_entrada
        migrations.RenameField(
            model_name='registroguardia',
            old_name='fecha_registro',
            new_name='fecha_entrada',
        ),
        # Update indexes (remove old, add new with fecha_entrada)
        migrations.RemoveIndex(
            model_name='registroguardia',
            name='ingresos_re_vehicul_1b15af_idx',
        ),
        migrations.RemoveIndex(
            model_name='registroguardia',
            name='ingresos_re_fecha_r_0267aa_idx',
        ),
        migrations.AddIndex(
            model_name='registroguardia',
            index=models.Index(fields=['vehiculo', '-fecha_entrada'], name='ingresos_re_vehicul_1b15af_idx'),
        ),
        migrations.AddIndex(
            model_name='registroguardia',
            index=models.Index(fields=['-fecha_entrada'], name='ingresos_re_fecha_r_0267aa_idx'),
        ),
    ]
