# Generated by Django 5.0.3 on 2025-11-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0007_add_fecha_salida_and_rename_fecha_entrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroguardia',
            options={'ordering': ['-fecha_entrada'], 'verbose_name': 'registro de guardia', 'verbose_name_plural': 'registros de guardia'},
        ),
        migrations.RenameIndex(
            model_name='registroguardia',
            new_name='ingresos_re_vehicul_b22dee_idx',
            old_name='ingresos_re_vehicul_1b15af_idx',
        ),
        migrations.RenameIndex(
            model_name='registroguardia',
            new_name='ingresos_re_fecha_e_e0fe75_idx',
            old_name='ingresos_re_fecha_r_0267aa_idx',
        ),
        migrations.AddField(
            model_name='ingresotaller',
            name='repuesto_necesario',
            field=models.CharField(blank=True, max_length=255, verbose_name='repuesto necesario'),
        ),
        migrations.AlterField(
            model_name='registroguardia',
            name='fecha_entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de entrada'),
        ),
        migrations.AlterField(
            model_name='registroguardia',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='fecha de salida'),
        ),
    ]
