# Generated by Django 5.0.3 on 2025-11-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0008_alter_registroguardia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresotaller',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('EN_PAUSA', 'En Pausa'), ('TERMINADO', 'Terminado'), ('RETIRADO', 'Retirado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20, verbose_name='estado'),
        ),
    ]
