# Generated by Django 5.0.3 on 2025-11-24 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0010_alter_solicitudingreso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresotaller',
            name='registro_guardia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_taller', to='ingresos.registroguardia', verbose_name='registro de guardia'),
        ),
    ]
