# Generated by Django 5.0.3 on 2025-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0011_ingresotaller_registro_guardia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='estado'),
        ),
    ]
