# Generated by Django 5.0.3 on 2025-11-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0012_tarea_fecha_inicio_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudingreso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada'), ('RETIRADA', 'Retirada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='estado'),
        ),
    ]
