# Generated by Django 5.0.3 on 2025-11-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0013_alter_solicitudingreso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroguardia',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='modelo'),
        ),
    ]
