# Generated by Django 5.0.3 on 2025-11-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0014_registroguardia_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora de fin')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='fecha y hora de inicio')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horarios', to='ingresos.ingresotaller', verbose_name='ingreso')),
            ],
            options={
                'verbose_name': 'bloque horario',
                'verbose_name_plural': 'bloques horarios',
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['ingreso', 'fecha'], name='ingresos_ag_ingreso_91deb8_idx'), models.Index(fields=['fecha', 'hora_inicio'], name='ingresos_ag_fecha_6602ff_idx')],
                'unique_together': {('ingreso', 'fecha', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
