# Generated by Django 5.0.3 on 2025-11-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0015_agendabloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresotaller',
            name='hora_fin',
            field=models.PositiveIntegerField(blank=True, help_text='Hora de fin (0-23)', null=True, verbose_name='hora de fin'),
        ),
        migrations.AddField(
            model_name='ingresotaller',
            name='hora_inicio',
            field=models.PositiveIntegerField(blank=True, help_text='Hora de inicio (0-23)', null=True, verbose_name='hora de inicio'),
        ),
        migrations.DeleteModel(
            name='AgendaBloque',
        ),
    ]
