# Generated by Django 5.0.3 on 2025-11-25 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0016_ingresotaller_hora_fin_ingresotaller_hora_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresotaller',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='ingresotaller',
            name='hora_inicio',
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre de la máquina')),
                ('tipo', models.CharField(choices=[('ELEVADOR_3D', 'Elevador 3D'), ('ELEVADOR_TIJERA', 'Elevador de Tijera')], max_length=20, verbose_name='tipo de máquina')),
                ('numero', models.PositiveIntegerField(help_text='Identificador numérico de la máquina', verbose_name='número de máquina')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'máquina',
                'verbose_name_plural': 'máquinas',
                'ordering': ['tipo', 'numero'],
                'unique_together': {('tipo', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='ingresotaller',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='ingresos.maquina', verbose_name='máquina asignada'),
        ),
    ]
