# Generated by Django 5.0.3 on 2025-10-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, verbose_name='patente')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='modelo')),
                ('año', models.PositiveIntegerField(verbose_name='año')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN')),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta'), ('FURGON', 'Furgón'), ('OTRO', 'Otro')], default='CAMION', max_length=20, verbose_name='tipo de vehículo')),
                ('flota', models.CharField(blank=True, max_length=50, verbose_name='flota')),
                ('kilometraje', models.PositiveIntegerField(default=0, verbose_name='kilometraje')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['patente'],
                'indexes': [models.Index(fields=['patente'], name='vehiculos_v_patente_48e85b_idx'), models.Index(fields=['activo'], name='vehiculos_v_activo_e6f381_idx')],
            },
        ),
    ]
