# Generated by Django 5.0.3 on 2025-11-19 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo de documento')),
                ('archivo', models.FileField(upload_to='vehiculos/', verbose_name='archivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='fecha de subida')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_vehiculo', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'documento de vehículo',
                'verbose_name_plural': 'documentos de vehículo',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
