# Generated by Django 5.0.3 on 2025-11-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_documentovehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentovehiculo',
            old_name='tipo',
            new_name='tipo_documento',
        ),
    ]
